# Validates the yaml
name: validate_yaml
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # run once a day
  schedule:
    - cron: '31 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate_yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Java Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: java
          config-file: openapi.yaml
